<?php
/** @var $this Lanot_Attachments_Block_Abstract */
if ($this->hasItems()):
    $helper = Mage::helper('lanot_attachments/file');
    $config = Mage::helper('lanot_attachments/config');
    $type = $this->getEntityType();
?>
<div class="lanot-attachments <?php echo $config->getClassBlock($type)?>">
    <div class="lanot-attachments-title <?php echo $config->getClassTitle($type)?>">
        <strong><span><?php echo $config->getTitle($type)?></span></strong>
    </div>
    <div class="lanot-attachments-content <?php echo $config->getClassContent($type)?>">
        <ul>
            <?php foreach ($this->getCollection() as $item): ?>
            <li class="la-icon <?php if ($config->canShowIcons()): ?>la-icon-<?php echo $item->getType(); ?> la-icon-<?php echo str_replace('.', '_', $helper->getFileExtension($item)); ?><?php endif;?>">
                <a href="<?php echo $item->getAttachmentUrl();?>" <?php if ($config->canShowNewWindow()): ?>target="_blank"<?php endif;?>>
                    <?php echo $item->getTitle();?>
                </a>
            </li>
            <?php endforeach;?>
        </ul>
    </div>
</div>
<?php endif; ?>